folio-org/ui-checkout

- settings/EntrySelector.js
index.js makes use of `Settings`, which has a hard-coded width of 25%,
for the list of available settings. Thus the `PaneSet` here with a
width of 80% caused the window to scroll horizontally.
> fix horizontal scroll

- CHANGELOG.md
- package.json
Apps should not depend explicitly on plugins. The WHOLE POINT of a
plugin is that it can be switched out at runtime. Also, the fact that
this was a hard dep on version 1.0.0 rather than, say, ^1.0.0, appears
to have caused multiple copies of the plugin and of its dependencies to
be built into the bundle and that caused no end of trouble.
> rm fixed dependency on ui-plugin-find-users 1.0.0

- lib/UserDetail/UserDetail.js
It turns out that in some contexts JSX will render falsy integer values
as integers and sometimes as booleans. `hasProfilePicture` is only used
in a boolean context here, so it is now casted to boolean.
> cast boolean-ish value to boolean. Refs UICHKOUT-42

- lib/PatronForm/PatronForm.js
Resolves [UICHKOUT-46](https://issues.folio.org/browse/UICHKOUT-46):
This creates a method `onCloseModal` which clears the search modal, and passes it forward into the find user plugin. Depends on other PRs: [ui-plugin-find-user](https://github.com/folio-org/ui-plugin-find-user/pull/10), [ui-users](https://github.com/folio-org/ui-users/pull/221), [stripes-smart-components](https://github.com/folio-org/stripes-smart-components/pull/80)
> Clearing modal in onCloseModal and passing it to props

- CHANGELOG.md
- test/ui-testing/error_messages.js
The Settings pages moved from auto-save-on-change to
you-must-click-submit-to-save. This change clicks the save button to be
sure the required setting is stored.
Fixes [UITEST-20](https://issues.folio.org/browse/UITEST-20).
> save changes to Settings > Circ > Scan ID form

- CHANGELOG.md
- lib/PatronForm/PatronForm.js
- translations/en.json
Now that table headers may be i18n'ed, they must be referred to by their
keys, which are constant, rather than their values, which will change
with each translation.
Fixes [UICHKOUT-411](https://issues.folio.org/browse/UICHKOUT-411)
> pass keys, not values, to MCL.

- CHANGELOG.md
- package.json
Following the change in name of the metadata property (from metaData to metadata) the circulation interface version needs updating (from 2.2 to 3.0)
> Update circulation interface dependency UICHKOUT-420

- CHANGELOG.md
- Scan.js
- lib/UserDetail/UserDetail.js
- lib/ViewPatron/ViewPatron.js
* Open Loans count is now a link to the borrower's open loans page.
* Moved the loans count rendering into `<UserDetail>`
* Turned `<ViewPatron>` into a presentation component by removing it's connected-ness in an effort to centralise data-fetching.
> UICHKOUT-424: Added link to borrower's open loans

- test/ui-testing/error_messages.js
"evaluate" returns a promise, so I believe the issue here is that things
are executing asynchronously and the changes inside the previous
handler, aiming to turn all buttons off, were executing after the save
button was clicked but before navigating away, which caused an "unsaved
changes; do you really want to leave?" prompt to prevent navigating on
to the next test.
> handle "evaluate" clauses in order

- test/ui-testing/error_messages.js
This is probably what's happening without the wait(1111) before evaluate:
- test waits for check-boxes to appear (data for populating them may
still be loading after they appear)
- test looks for check-boxes that are checked but finds none (if
data didn't load yet)
- data finish loading and the username checkbox is typically populated
with a check-mark
- assuming that username is NOT checked at this point, the test clicks
it, thereby un-checking it
- no checkboxes are thus selected and at least one needs to be,
so the form cannot be saved
- test clicks 'Save' to no effect
- test tries to leave form, and the 'Unsaved changes' modal
comes up.
> Wait for checkbox settings to load before clicking any UITEST-16

- CHANGELOG.md
- package.json
The stripes-components dependency was out of sync with stripes-core,
which was causing funky overlaps of the settings pane where the third
column would be superimposed on the second. This probably means we have
our Pane and Paneset components in the wrong repository, or maybe that
we are managing that dependency incorrectly. In any case, the version of
stripes-components we get from stripes-core needs to be the same as the
one we depend on here. And now it is.
> consistent stripes-components dep with stripes-core

- util.js
- Users of that function were expecting a falsey value if unavailable, not an empty Object.
> Return undefined from getCheckoutSettings when there are none

- Scan.js
- ScanItems.js
Checkout settings aren't initialised to anything at the start so a brand new build would hit that if-condition and return an empty div after the fix to the checkout test yesterday.
This lets us render, but the user of `checkoutSettings` has a default value to ensure they don't attempt to index into an undefined variable.
> Fixed bug where page wouldn't render w/o settings init'd

- CHANGELOG.md
- test/ui-testing/error_messages.js
Click out to the settings app bewteen each round of tests to increase
idempotence of the tests. The app needs to be in its virgin state (all
fields empty) at the start of each test in order for those tests to
correctly assess the error messages each test generates. Here, a value
in the item barcode field with an empty patron field causes an error on
the patron-field. But that makes it impossible to test the patron-field
because an error message (albeit, the wrong one) is already present on
the patron field, causing the test to fail. We could add a timer to the
middle of the patron field test to give the (expected-to-fail) patron
lookup function more time to fail, but timers are unreliable.
Arguably, resetting the app between tests is the _right_ approach
anyway. Too bad we don't have a …
> reset app between tests

- src/Scan.js
- src/ScanItems.js
- src/components/ErrorModal/ErrorModal.js
- src/components/ItemForm/ItemForm.js
- src/components/PatronForm/PatronForm.js
- src/components/ScanFooter/ScanFooter.js
- src/components/ScanTotal/ScanTotal.js
- src/components/UserDetail/UserDetail.js
- src/components/ViewItem/ViewItem.js
- src/components/ViewPatron/ViewPatron.js
- src/index.js
- src/util.js
- translations/ui-checkout/en.json
Taking into account that retrieving the intl object from this.context.intl or the stripes god object (stripes.intl) is a deprecated pattern.
The purpose of this PR is to update this repo to only use react-intl constructs outlined at https://github.com/folio-org/stripes-core/blob/master/doc/i18n.md
React Intl docs: https://github.com/yahoo/react-intl/wiki
> UICHKOUT-450: Use documented react-intl patterns instead of stripes.intl

- src/Scan.js
- src/ScanItems.js
- src/components/ErrorModal/ErrorModal.js
- src/components/ItemForm/ItemForm.js
- src/components/PatronForm/PatronForm.js
- src/components/UserDetail/UserDetail.js
- src/components/ViewItem/ViewItem.js
- src/components/ViewPatron/ViewPatron.js
Adding `injectIntl()` in a few extra places in https://github.com/folio-org/ui-checkout/pull/196 starting throwing console warnings like:
```
Warning: Failed prop type: Invalid prop `forwardedRef` of type `Object` supplied to `PatronForm`, expected instance of `Element`.
```
By sticking to just `<FormattedMessage>`, `<FormattedDate>`, and `<FormattedTime>` components, we can avoid issues around `injectIntl()`.
> UICHKOUT-450 Replace formatMessage() with <FormattedMessage>

- package.json
- src/ScanItems.js
Provide `servicePointId` during checkout. This is required by Okapi interface version circulation v5.0.
Refs [UICHKOUT-460](https://issues.folio.org/browse/UICHKOUT-460)
> Provide servicePointId during checkout

- CHANGELOG.md
- src/components/PatronForm/PatronForm.js
`active` is the attribute on the user-object, but the formatter for this
field is named `status` because, um, I don't remember why but that's what
it's called now. So the `<Pluggable>` needs to ask for `status` rather
than `active` for that data to be correctly formatted in the modal.
Fixes [UICHKOUT-472](https://issues.folio.org/browse/UICHKOUT-472)
> use the "status" formatter for the "active" attr

- src/Scan.js
PR #210 added an extra `catch` block that does not correctly report all
the attributes (specifically, `patron`) that are made available to it
via the `throw` statement above when a patron cannot be found. This
prevents display of the "user not found" error message.
> remove extraneous throw clause

- package.json
- test/bigtest/.eslintrc.js
- test/bigtest/helpers/setup-application.js
- test/bigtest/index.js
- test/bigtest/interactors/application.js
- test/bigtest/network/boot.js
- test/bigtest/network/config.js
- test/bigtest/network/index.js
- test/bigtest/network/scenarios/default.js
- test/bigtest/tests/application-test.js
https://issues.folio.org/browse/UICHKOUT-476
We want to add both unit test coverage to the users application, and also add the ability to start the application in mirage mode so that development can be done without having to actually be connected to any kind of server environment.
This adds BigTest and Mirage to the ui-checkout app using the emerging standard bigTest setup of models/serializers/factories going into the tests/bigTest directory.
> UICHKOUT-476: Setup Big Test infrastructure

- CHANGELOG.md
- src/components/ItemForm/ItemForm.js
https://issues.folio.org/browse/UICHKOUT-482
This PR improves the item barcode focus. Previously after checkout has been executed the focusing would end up in an infinite loop causing the checkout module to hang forever. This was happening because `submitSucceeded` from redux-form would stay set to `true`. Reseting the item form after successful checkout resolves the issue.
> Adjust item form focus. Fixes UICHKOUT-482.

- CHANGELOG.md
- test/ui-testing/error-messages.js
- test/ui-testing/test.js
Changes to the aria attributes in MCL must be reflected in the
integration tests as well.
Refs [UICHKOUT-490](https://issues.folio.org/browse/UICHKOUT-490), [STCOM-365](https://issues.folio.org/browse/STCOM-365)
> integration tests must accommodate MCL aria changes

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UICHKOUT-492
> Update circulation OKAPI interface to v7.0. Part of UICHKOUT-492.

- test/ui-testing/error-messages.js
folio-org/ui-plugin-find-user/pull/66 changed the way
ui-plugin-find-user provides module information when the plugin is
instantiated. This caused the results-list for a plugin's search to
change from `list-users` to `list-plugin-find-user` because the element
ID is, apparently, constructed from the module ID and we had a bunch of
tests whose selectors needed updating.
Arguably, that PR does The Right Thing by causing the plugin's ID to be
unique instead of matching that of the app it consumes, but it also
highlights the larger issue that plugins really should not be consuming
apps in this manner. It's borderline illegal and just gross.
Aside, this test should be moved to platform-core as, by including a plugin,
it's clearly an integration test rather than a unit test.
Refs …
> use correct identifier for plugin's list

- test/ui-testing/error-messages.js
ui-plugin-find-users no longer applies an `<a>` around its rows, so
tests that use the plugin must be updated to reflect this.
> sync tests with update plugin markup

- CHANGELOG.md
- src/util.js
Searches by patron ID must use an exact match, not a wildcard.
Fixes [UICHKOUT-510](https://issues.folio.org/browse/UICHKOUT-510)
> use exact match for patron IDs

- package.json
- test/ui-testing/error-messages.js
Apps are guaranteed to show up in the app-menu but not on the navigation
bar, so tests need to navigate by clicking menu items.
Refs [UITEST-65](https://issues.folio.org/browse/UITEST-65)
> navigate via the app-menu instead of icons

- src/components/PatronForm/PatronForm.js
To allow user navigate to patron look-up link by keyboard
https://issues.folio.org/browse/UICHKOUT-509
#Screenshot
> UICHKOUT-509 - Keyboard navigation ignores Patron look-up link

- package.json
Add missing permissions to the "Check out: all" pset that are necessary
for users with fees/fines or manual blocks.
Refs [UIU-1078](https://issues.folio.org/browse/UIU-1078)
> UIU-1078 checkout permissions

- package.json
Add missing permissions to the "Check out: all" pset that are necessary
to check things out. Any things. Seriously, how did I miss this until
now?
Refs [UIU-1078](https://issues.folio.org/browse/UIU-1078)
> add missing permissions

- src/ScanItems.js
- src/components/ErrorModal/ErrorModal.js
- src/components/ItemForm/ItemForm.js
- translations/ui-checkout/en.json
Add loan policy name to error modal on override.
https://issues.folio.org/browse/UICHKOUT-534
> UICHKOUT-534 - Override non-circulating loan policy does not report name of loan policy

- CHANGELOG.md
- test/bigtest/interactors/check-out.js
In accordance with the fact that now MCL rows are not always a `div`.
> Handle tests 

- test/ui-testing/error-messages.js
Nightmare appears to be getting hung up in some MCL selections. I'm not
sure how this is coming up now given that this passed for several days,
but here we are. Removing some of the markup and leaving the selector to
stand on semantic markup alone seems to do the trick.
Refs [UITEST-70](https://issues.folio.org/browse/UITEST-70)
> UITEST-70 be less markupy, more semantic

- CHANGELOG.md
- src/components/UserDetail/UserDetail.js
UIREQ-325: Handle issue regarding request link is not showing requests awaiting pickup on the checkout page
> UIREQ-325: Handle issue regarding request link

- package.json
Reverts folio-org/ui-checkout#380
Reverting only so we can tag a patch release at tip-of-master; this is the only feature-commit since v1.11.0 was released and reverting (and then reapplying) a single PR will be easier than cherry-picking everything since this PR onto a release branch. Yes, yes, we may want to investigate a different branching strategy like GitFlow in the long term to mitigate this process. Today, I just need to publish a release.
> Revert "UICHKOUT-543: Update the circulation API to support changes in the rule editor"

- CHANGELOG.md
- src/components/ViewItem/ViewItem.js
Make change the due date button available on checked out loans when a user has loan edit permission as part of [UIU-1177](https://issues.folio.org/browse/UIU-1177). This permission works in conjunction with permissions for the loans check out.
> UIU-1177: Make change the due date button available on checked out loans when a user has loan edit permission

- CHANGELOG.md
- src/util.js
Do not include items with the request-status `Closed - pickup expired`
when searching for a user's requests during checkout.
Refs [UICHKOUT-553](https://issues.folio.org/browse/UICHKOUT-553)
> UICHKOUT-553 better handling for expired requests

- test/ui-testing/error-messages.js
The code for plucking a user from the patron-look-up pop-up could allow
for `diku_admin`, a user without a barcode, to be selected. This caused
issues with downstream tests that expect the user to have a barcode.
> avoid diku_admin in tests

- test/ui-testing/error-messages.js
The code for plucking a user from the patron-look-up pop-up could allow
for `diku`, a user without a barcode, to be selected. This caused
issues with downstream tests that expect the user to have a barcode.
Somebody utterly botched an earlier attempt to do this exact thing in
PR #404 but must have pushed up the wrong branch because that only
contained an extra timer, useful for inspecting what happened in the
test, but useless in terms of actually fixing it. What a moron. Another
nail in the coffin for having the privilege of merging your own PRs.
Sure, it can be expedient, but it can also be stupid. I am living
proof.
> avoid admin users in tests

- CHANGELOG.md
- package.json
Implement **Check out: Check out circulating items** permission as part of [UICHKOUT-535](https://issues.folio.org/browse/UICHKOUT-535). The only difference at the moment with existing **Check out: All permissions** permission is that the later also allows overriding of non-circulating loan policies.
> UICHKOUT-535: Implement check out circulating items permission

- CHANGELOG.md
- package.json
Extend _okapiInterfaces_ with _inventory_ interface in order to handle permissions error on _folio-snapshot_ environment.
> UICHKOUT-562: Extend "okapiInterfaces" with "inventory" in order to handle permissions error

- CHANGELOG.md
- package.json
- src/ScanItems.js
- src/components/ViewItem/ViewItem.js
- test/bigtest/interactors/check-out.js
- test/bigtest/tests/check-out-test.js
Hide the empty checkout items list message during the checkout of the new item in the scope of [UICHKOUT-557](https://issues.folio.org/browse/UICHKOUT-557).
> UICHKOUT-557: Hide the empty checkout items list message during the checkout

- CHANGELOG.md
- package.json
- src/components/ErrorModal/ErrorModal.js
1) Add "circulation.end-patron-action-session.post" sub-permission in order to prevent error when a user has either "Check out: All permissions" or "Check out: Check out circulations items" permissions.
2) Show the proper message when user is not able to override the loan policy
> Add "circulation.end-patron-action-session.post" sub-permission

- CHANGELOG.md
- src/components/UserDetail/UserDetail.js
Fix link to loans list in user details information in the scope of the ticket [UICHKOUT-554](https://issues.folio.org/browse/UICHKOUT-554).
> UICHKOUT-554: Fix link to loans list in user details information

- src/CheckOut.js
- src/ScanItems.js
- src/components/ItemForm/ItemForm.js
[UICHKIN-142](https://issues.folio.org/browse/UICHKIN-142)
After performing an automatic checkout of an item, all subsequent attempts to automatically checkout an item fail, because the item barcode field is not populated with a value. This PR fixes that bug.
> UICHKIN-142: fix bug with item barcode not populated on automatic checkout

- CHANGELOG.md
- src/components/ErrorModal/ErrorModal.js
- src/components/OverrideModal/OverrideModal.js
- src/constants.js
- test/ui-testing/error-messages.js
Handle the wrong error message when checking out the requested items to non-requester which was introduced as a part of #422. The current issue is affecting other types of errors as well.
> UICHKOUT-580: Handle the wrong error message when checking out requested items to non-requester

- CHANGELOG.md
- package.json
Why a new major version?
* bump the `@folio/stripes` peer to `v3.0.0`
* move `react-router` related things to peerDependencies
* move `react-intl` to peerDependencies
> bump to version 3.0.0

- CHANGELOG.md
- package.json
Update the optional-dep on plugin-find-user to one that uses a
compatible version of `@folio/stripes`.
> upgrade plugin-find-user to v2.0.0

- src/CheckOut.js
Clean up patronId from activeRecord in case when session was closed.
https://issues.folio.org/browse/UICHKOUT-607
> UICHKOUT-607 - Three identical e-mail notices for one checkout

- CHANGELOG.md
- src/ScanItems.js
- src/components/MultipieceModal/MultipieceModal.js
- test/bigtest/interactors/check-out.js
- test/bigtest/interactors/checkout-note-modal.js
- test/bigtest/interactors/multipiece-modal.js
- test/bigtest/tests/check-out-test.js
https://issues.folio.org/browse/UICHKOUT-610
https://issues.folio.org/browse/UICHKOUT-611
This fixes a bug that would cause the UI to get stuck if one of the two modals (multipiece or checkout notes) were cancelled during the checkout process. The Enter button would be disabled, making it impossible to check out other items without ending the session. 
The new behavior clears the barcode input field and re-enables the Enter button so scanning can continue blissfully.
> UICHKOUT-610/611: Fix bug preventing continuation after cancelling checkout notes or multipiece modal.

- CHANGELOG.md
- src/ScanItems.js
Fix bug preventing continuation after cancelling checkout notes or multipiece modal 
Refs [UICHKOUT-610](https://issues.folio.org/browse/UICHKOUT-610), [UICHKOUT-611](https://issues.folio.org/browse/UICHKOUT-611)
> UICHKOUT-610, -611 do not halt after closing modal

- package.json
The dev-dep on `@folio/stripes-components` MUST be a caret dep
compatible with the selected version of stripes, otherwise it risks
pulling multiple copies into the build because of a newer version
present in `@folio/stripes`.
This bug was introduced in #441 and inadvertently carried through other
updates but we didn't realize it until now, when `v6.1.0` was published,
putting it out of sync with the `~6.0` version here.
> @folio devdeps MUST use caret deps

- CHANGELOG.md
- package.json
Update `react-intl-safe-html` to `2.0` to maintain compatibility with
`react-intl` `4.5`.
Refs [STRIPES-672](https://issues.folio.org/browse/STRIPES-672)
> STRIPES-672 update react-intl-safe-html

- src/components/UserDetail/UserDetail.js
- src/components/ViewPatron/ViewPatron.js
- test/bigtest/interactors/check-out.js
- test/bigtest/interactors/proxy-modal.js
- test/bigtest/network/models/proxiesfor.js
- test/bigtest/network/scenarios/proxies.js
- test/bigtest/tests/proxy-test.js
`props.settings`, which is used to determine if a user's profile picture
should be displayed, but which we don't actually implement, was
inadvertently removed from the connected `UserDetail` component when
viewing a proxy, which caused an NPE, which made checkout-as-proxy
impossible to use.
IOW, a prop for a setting we _don't_ use broke a feature we _do_. Oy.
Restored the setting, and added some tests.
Refs [UICHKOUT-614](https://issues.folio.org/browse/UICHKOUT-614)
> UICHKOUT-614 restore checkout-as-proxy

- test/ui-testing/error-messages.js
The DOM structure of error messages changed a bit as part of the
migration off redux-form (yay!) to final-form, or possibly as part of
the migration from `react-intl` `v2.x` to `v4.x`. In any case, we need a
different selector for the error message.
Refs [UICHKOUT-593](https://issues.folio.org/browse/UICHKOUT-593)
> UICHKOUT-593 test updates

- CHANGELOG.md
- src/CheckOut.js
- src/components/UserDetail/UserDetail.js
- src/util.js
Use `==` instead of `=` when possible to take advantage of table indexes
and therefore issue more efficient queries.
Refs [CIRCSTORE-215](https://issues.folio.org/browse/CIRCSTORE-215)
> CIRCSTORE-215 use == for more efficient queries

- CHANGELOG.md
- src/CheckOut.js
- src/components/UserDetail/UserDetail.js
- src/util.js
Reverts folio-org/ui-checkout#498
Not so fast! As noted in [PREF-62](https://issues.folio.org/browse/PERF-62), we haven't actually tested all these queries for performance improvements yet. There are really only two rules in performance optimizations: 
1. measure first
1. only change _one thing_
This PR breaks 'em both. 🤦
> Revert "CIRCSTORE-215 use == for more efficient queries"

- CHANGELOG.md
- package.json
Increment `@folio/plugin-find-user` version to `^3` for
compatibility with `@folio/stripes` `4.0`.
> increment plugin-find-user to v3

- CHANGELOG.md
- src/CheckOut.js
- src/components/UserDetail/UserDetail.js
Use `==` instead of `=` for more efficient queries.
Refs [PERF-62](https://issues.folio.org/browse/PERF-62)
> PERF-62 use == for more efficient queries

- CHANGELOG.md
- src/components/UserDetail/UserDetail.js
https://issues.folio.org/browse/UICHKOUT-641 - Use right truncation to fetch all open requests.
As per @julianladisch:
> The CQL query status = Open is most likely an error. It returns all statuses that contain the word Open including "Closed - was Open before" (if such an status were existing).
status == "Open *" is probably what is intended and matches statuses that start with Open – all open request of the tenant. The appropriate index for this is b-tree "index" and not "fullTextIndex".
> UICHKOUT-641: Use right truncation operator to fetch user's open requests.

- CHANGELOG.md
- src/ScanItems.js
This turned out to be a problem with ui-checkout.  The module
was not providing the barcode of the proxy borrower when it
issued the check-out request, so as far as the back-end was
concerned, there was no proxy borrower.  I fixed this by
making the module check for the presence of proxy borrower
data, and include the proxy borrower's barcode if it was
present.
refs: https://issues.folio.org/browse/UICHKOUT-639
> UICHKOUT-639: Proxy borrower does not display on loan details

- CHANGELOG.md
- src/CheckOut.js
Previously, if a patron had a proxy relationship but was acting as self,
the checkout request object would include the patron's barcode in both
the `userBarcode` and `proxyUserBarcode` properties. Now, when acting as
self, the `proxyUserBarcode` property will be omitted.
Fixes [UICHKOUT-644](https://issues.folio.org/browse/UICHKOUT-644)
> UICHKOUT-644 ignore proxy when acting as self

- src/CheckOut.js
- src/ScanItems.js
* `fuggle`, verb, transitive: to screw something up
* `defuggle`, verb, transitive: to think you understand the problem when
in fact you do not, causing you to implement a fix that papers over the
issue without actually resolving it.
* `undefuggle`, verb, transitive: to truly understand the problem and
why the original "fix" didn't take, and to actually resolve the issue.
I don't know when this problem was originally fuggled, but the crux is
that the checkout API rejects requests that contain the same barcode for
both patron and proxy. #527 defuggled this by clearing out the proxy
value when a patron had sponsors but was acting as self. The hidden
problem was that the ProxyManager isn't smart enough to hide when
its patron and proxy values match; if a patron has sponsors and proxy is …
> UICHKOUT-644 better proxy handling

- CHANGELOG.md
- src/CheckOut.js
- translations/ui-checkout/en.json
This PR refactors the way the ui-plugin-create-inventory-records is being displayed in a similar fashion to what @K-Felk did in  https://github.com/folio-org/ui-inventory/pull/1134.
This allows for displaying the plugin in the right place and also for controlling the ScanFooter.
https://issues.folio.org/browse/UICHKOUT-650
> UICHKOUT-650: Hide ScanFooter when fast add record plugin is open

- CHANGELOG.md
- package.json
- test/bigtest/network/config.js
It looks like this module has been using
stripes five in both testing and production.
I did update react-router-dom
to 5.2, and fixed an unrelated problem that
was causing some errors to pop up during testing.
refs: https://issues.folio.org/browse/UICHKOUT-643
> UICHKOUT-643: increment @folio/stripes to v5

- CHANGELOG.md
- src/ModalManager.js
- src/components/UserDetail/UserDetail.js
- src/components/ViewItem/ViewItem.js
Use the stripes-components versions of `<FormattedDate>` and
`<FormattedTime>` because they do not choke on the timestamps that are
provided by some backend modules.
Refs [UICHKOUT-649](https://issues.folio.org/browse/UICHKOUT-649), [STCOM-659](https://issues.folio.org/browse/STCOM-659)
> UICHKOUT-649 handle malformed timestamps

- src/components/ViewItem/ViewItem.js
Citing https://issues.folio.org/browse/STRIPES-693
The new MCL column-width hint API allows you to set a maximum value - if the column can be rendered smaller it will be.
Additionally, i marked the MultiColumnList instance with a `key` prop so that if multiple items are added to the list, the width will refresh.
> Apply MCL column width hints API so columns can shrink to fit content.

- CHANGELOG.md
- package.json
Upgrade `react-intl` to `v5` since that is part of `@folio/stripes`
`v5`.
Refs [STRIPES-694](https://issues.folio.org/browse/STRIPES-694)
> STRIPES-694 react-intl v5

- CHANGELOG.md
- src/CheckOut.js
I simply wrapped an IfPermission around the button code in question.
It now only displays if you have fast add permission.
Refs: https://issues.folio.org/browse/UICHKOUT-646
> UICHKOUT-646: Fast add permission (Check out)

- CHANGELOG.md
- test/bigtest/network/scenarios/manualPatronBlocks.js
A hard-coded block-expiration date in a unit test prevented that test
from running successfully after that date.
Refs [UICHKOUT-668](https://issues.folio.org/browse/UICHKOUT-668)
> UICHKOUT-668 replace hardcoded date in test

- CHANGELOG.md
- src/components/OverrideModal/OverrideModal.js
- test/bigtest/network/scenarios/manualPatronBlocks.js
How gross is this hack? Let me count the ways.
It's gross by using breaks to set the height
So `<Datepicker>` will render full, in-sight
Instead of clipping first or final days.
`usePortal` pops it out, but sets its place
From _modal_'s `y` position, hardly right,
And so ensues a render offset fight.
It's gross but so so simple, earning praise?
It's gross and leaves a rake to later bruise
Oneself by all who place a month with faith
That it will show, unclipp'd, no edge to lose.
You'll fix the stripes-component? Hold my breath
I'll not. There, CSS collects its dues.
You love my gross fix. It's simple. Like death.
Refs [UICHKOUT-666](https://issues.folio.org/browse/UICHKOUT-666)
> UICHKOUT-666 stretch the OverrideModal's height

- package.json
Move `moment` to a peer dependency so it can be correctly provided by
the platform in a version compatible with all other modules.
Refs [UICHKOUT-664](https://issues.folio.org/browse/UICHKOUT-664)
> UICHKOUT-664 move moment to peer

- CHANGELOG.md
- src/components/ViewItem/ViewItem.js
- test/bigtest/tests/check-out-test.js
- translations/ui-checkout/en_US.json
It looks like the sort implementation got confused between column
aliases, which contain the displayed (i.e. i18n'ed) values, and column
names, which contain their code points. It's possible that before we had
correct i18n, the alias pointed to a simple string like `Barcode` rather
than a `<FormattedMessage id="barcode">` object that is meaningless
from a sorting point of view, as this was the original implementation
in PR #27.
Refs [UICHKOUT-513](https://issues.folio.org/browse/UICHKOUT-513)
> UICHKOUT-513 restore item-list sort

- CHANGELOG.md
- src/components/ViewItem/ViewItem.js
[UIU-1536](https://issues.folio.org/browse/UIU-1536)
Removing "Users: User loan edit" permission.
Replacing it with "Users: User loans change due date".
Currently, the "Users: User loan edit" permission allows the user to change the due date, but with CIRC-647, that permission is no longer needed.
The edit permission was only added to that list in order to enable users to change due date, since there wasn't a change due date API at the time. 
- Do JIRAs exist to update the …
> UIU-1536 replace ui-users.loans.edit with ui-users.loans.change-due-date

- CHANGELOG.md
- package.json
- src/CheckOut.js
ui-plugin-create-inventory-records has a new major version v2 in development. [As part of that, I've added breaking changes in this PR.](https://github.com/folio-org/ui-plugin-create-inventory-records/pull/45) This PR handles those changes.
- Remove IfPermission which is now being handled in the plugin.
- Switch to usage of `renderTrigger` instead of `buttonVisible` and a separate trigger render.
- Remove state variables since were now letting the plugin manage its visibility state
> Upgraded to create-inventory plugin v2.0.0.

- CHANGELOG.md
- test/bigtest/interactors/error-modal.js
- test/bigtest/tests/check-out-test.js
https://issues.folio.org/browse/UICHKOUT-669
The prevention functionality was built on the BE. On FE, it was necessary to make sure that it works correctly and cover it with tests.
> UICHKOUT-669: Prevent check out for intellectual item status

- package.json
The `@folio/stripes` peer dependency was out of sync with its dev-deps.
The `@folio/react-intl-safe-html` dependency was out of sync with the
version of `react-intl` in its peer-dep.
Refs [UICHKOUT-690](https://issues.folio.org/browse/UICHKOUT-690)
> UICHKOUT-690 dependency cleanup

- CHANGELOG.md
- src/ModalManager.js
- src/constants.js
- src/util.js
- test/bigtest/tests/check-out-test.js
- translations/ui-checkout/en.json
https://issues.folio.org/browse/UICHKOUT-671
Before checking out an item with one of the statuses (`Long missing`, `In process (non-requestable)`, `Restricted`, `Unavailable`, `Unknown`), the user must confirm this.
> UICHKOUT-671: Add confirmation modal for 5 new item statuses

- CHANGELOG.md
- package.json
- src/ScanItems.js
- test/bigtest/network/config.js
- translations/ui-checkout/en.json
- remove unused endpoint `POST /circulation/override-check-out-by-barcode`.
- remove unused permission `circulation.override-check-out-by-barcode.post`.
https://issues.folio.org/browse/UICHKOUT-680
> UICHKOUT-680: Remove unused endpoint and permission

- CHANGELOG.md
- src/components/ItemForm/ItemForm.js
Adds support for an optional `readyPrefix` property at the module level in stripes.config.js. If set, this prefix will be displayed in the title when the app is ready to receive a scanned item barcode.
> UICHKOUT-686 Optional prefix to indicate scan readiness in title

- CHANGELOG.md
- src/components/ErrorModal/ErrorModal.js
- src/constants.js
- test/bigtest/constants.js
- test/bigtest/network/scenarios/errorsList.js
Item level error at check out displays two errors that essentially mean the same thing
https://issues.folio.org/browse/UICHKOUT-695
**Before**
**After**
> UICHKOUT-695: Do not show specific error

- CHANGELOG.md
- package.json
The only breaking change in `circulation` `10.0` was the removal of the
`override-check-out-by-barcode` which is not used here, hence continuing
to support `9.0`.
Refs [UICHKOUT-710](https://issues.folio.org/browse/UICHKOUT-710)
> UICHKOUT-710 also support circulation 10.0

- CHANGELOG.md
- package.json
There is a breaking change in mod-circulation (https://github.com/folio-org/mod-circulation/pull/854), circulation interface version will be updated to 11.0.  Other modules should update their dependencies to support this change.
**Do not merge. We have several associated pull request and we need merge them at the same time.**
**API changes**
circulation/override-renewal-by-barcode - will be removed
circulation/renew-by-barcode - request and response will be changed
Current changes will be effect ui-users module
https://issues.folio.org/browse/UICHKOUT-716
> UICHKOUT-716: Update circulation interface dependency to support v11

- CHANGELOG.md
- package.json
Avoid using `*.all` permission sets as they are usually over-permissive. 
Refs UICHKOUT-724
> UICHKOUT-724 avoid *.all permissions

- CHANGELOG.md
- src/components/UserDetail/Loans.js
- test/bigtest/network/config.js
- test/bigtest/tests/check-out-test.js
This PR takes care of 3 different tickets:
https://issues.folio.org/browse/UICHKOUT-727
https://issues.folio.org/browse/UICHKOUT-728
https://issues.folio.org/browse/UICHKOUT-729
It adds some extra permission checks in order to show links to loans, requests and accounts.
> UICHKOUT-727: Add extra permission checks for links loans, requests and accounts

- CHANGELOG.md
- src/CheckOut.js
Hide `ScanFooter` when fast add record plugin is open.
https://issues.folio.org/browse/UICHKOUT-720
> UICHKOUT-720: Hide ScanFooter when fast add record plugin is open

- CHANGELOG.md
- src/components/OverrideModal/OverrideModal.css
- src/components/OverrideModal/OverrideModal.js
* date picker on circulation override cuts off after 4 weeks
* make consistent modal footer with buttons located on the modal's edges
https://issues.folio.org/browse/UICHKOUT-731
**Before**
**After**
> UICHKOUT-731: Change modal layout

- CHANGELOG.md
- src/ScanItems.js
Replace `moment.format()` with `moment.toISOString()` because the
former does not guarantee the numbering system will be `Latn` (0-9,
Arabic numbers). Documentation not withstanding
(https://momentjs.com/docs/#/displaying/format/), what `.format()`
actually does is use the same tokens as for ISO-8601 but without
changing the numbering system. Thus, in a locale with a non-Latn
numbering system, e.g. where 0-9 are represented by a-j, a year-format
like `YYYY` could be returned as `cacb` instead of `2021`.
In fact, this is precisely what happens when the locale is set to `ar`
(Arabic, with a numbering system of Arabic-Hindi numerals, denoted
`Arab`, as opposed to Arabic numerals, denoted `Latn` ([don't ask](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ …
> UICHKOUT-732 provide loan-date in ISO-8601 format

- CHANGELOG.md
- src/ModalManager.js
Validate shape of circulation notes before accessing their nest
attributes. Some attributes may be empty in notes created via
migrations.
Refs [UICHKOUT-736](https://issues.folio.org/browse/UICHKOUT-736)
> UICHKOUT-736 validate shapes to avoid NPEs on optional attributes

- CHANGELOG.md
- Jenkinsfile
- src/CheckOut.js
by https://issues.folio.org/browse/UICHKOUT-739.
Blocker is not related to current implementation 
This piece of code that was removed is redundant and does nothing except causes buggy behavior (when we're doing checkout bunch of items for different patrons, when patron is changed and timer is restarting there was the moment when `activeRecord` became empty and session was ended). We do not need to end session if `activeRecord` is empty because it will be finished anyway with timeout if there is patron, IOW, we do not need to end session when nothing was happened.
https://issues.folio.org/browse/UICHKOUT-730
> UICHKOUT-730: While checking out items the patron barcode disappears without inactivity

- CHANGELOG.md
- src/components/UserDetail/Loans.js
We have requirement to always display fee/fine decimal places on Checkout page.
Also now number formatting for suspended fee/fine based on user locale is missing. **FormattedNumber** react component should be used to have such formatting.
**FormattedNumber** react component does _not_ display decimal places if decimal places have zero values. For example if a value is "**10.00**" **FormattedNumber** will render just "**10**" without decimal places.
**FormattedNumber** has _minimumFractionDigits_ property which allows to always render as many decimal places as we need. In our case it should be 2.
Before:
After:
https://issues.folio.org/browse/UICHKOUT-742
> UICHKOUT-742: Always display fee/fine decimal places on Checkout page

- CHANGELOG.md
- src/CheckOut.js
The auto submission worked fine in the past so I'm not sure `bubbles` is not required. I wonder if this has changed after we upgraded to react 17. 
https://issues.folio.org/browse/UICHKOUT-756
> UICHKOUT-756: Fix auto checkout of items with delivery requests

- CHANGELOG.md
- package.json
- src/components/OverrideModal/OverrideModal.js
- src/constants.js
- test/bigtest/tests/override-patron-blocks-test.js
DueDatePicker is incorrectly instantiated
According to PO's сomment in ticket, we can preffil `date` field with current date.
To correctly show date at UI (according to time zone of tennant) and send it at back-end (in UTC), we need some magic, which happen in `getInitialValues` function.
https://issues.folio.org/browse/UICHKOUT-693
> UICHKOUT-693: DueDatePicker is incorrectly instantiated

- CHANGELOG.md
- package.json
Compile Translation Files into AST Format.
- Destination folder was renamed for consistency with other modules (Just for example https://github.com/folio-org/ui-users/blob/master/package.json#L843)
- We run locally command "yarn formatjs-compile" and we don't get any errors.
https://issues.folio.org/browse/UICHKOUT-708
Hello @zburke 
Could you please confirm that Jenkinsfile are deprecated and we don't need add 
`runScripts = [
['formatjs-compile': ''],
]`
to Jenkinsfile.?
> UICHKOUT-708: Compile Translation Files into AST Format

- CHANGELOG.md
- src/ScanItems.js
- test/bigtest/tests/override-loans-policy-test.js
Remove unnecessary request to `loan-policy-storage/loan-policies` end-point within checkout procedure.
I've checked where and how data from this endpoint is using, and found that we need only policy name, which is already in responce from `circulation/check-out-by-barcode` end-point. Also we need `lostItemPolicyId` to create link to policy, but it's present at top level of  `circulation/check-out-by-barcode` responce too.
I checked workability of checkout procedure and case with not loanable item - works as expected.
https://issues.folio.org/browse/UICHKOUT-767
> UICHKOUT-767: remove request to `loan-policy-storage/loan-policies` end-point

- CHANGELOG.md
- src/components/PatronForm/PatronForm.js
According to [changes](https://github.com/folio-org/ui-plugin-find-user/pull/199) in `ui-plugin-find-user` to solve the problem with focus, we should additionaly pass `restoreFocus` into `Pluggable` component.
https://issues.folio.org/browse/UICHKOUT-773
> UICHKOUT-773: fix focus issue

- CHANGELOG.md
- package.json
- src/CheckOut.js
- src/ModalManager.js
- src/components/ErrorModal/ErrorModal.js
- src/components/MultipieceModal/MultipieceModal.js
- src/components/OverrideModal/OverrideModal.js
Refactor away from react-intl-safe-html because its features are now natively supported by react-intl and its config in stripes-core
> UICHKOUT-721 - refactor away from react-intl-safe-html

- CHANGELOG.md
- package.json
Optional dependency `@folio/circulation` is out of date
https://issues.folio.org/browse/UICHKOUT-777
> UICHKOUT-777: optional dependency @folio/circulation is out of date

- CHANGELOG.md
- src/ScanItems.js
Enable error message when entering an item barcode without a patron barcode
[UICHKOUT-770](https://issues.folio.org/browse/UICHKOUT-770)
> Enable error message when entering an item barcode without a patron barcode

- package.json
GA builds can require NodeJS v16, but ATM the platform is still built on
Jenkins where v14 is the standard.
Refs [UICHKOUT-782](https://issues.folio.org/browse/UICHKOUT-782)
> UICHKOUT-782 back node to v14

- CHANGELOG.md
- src/util.js
- src/util.test.js
When formatting a name, handle empty-string values the same way as other
falsy values. Previously, the formatter only checked if values were null
or undefined; empty-string values were ignored. This led objects like
```
{
firstName: "Andrea",
preferredFirstName: "",
lastName: "Andromeda"
}
```
to be formatted as "Andromeda" instead of "Andromeda, Andrea" because
`preferredFirstName` was non-null. Now, undefined, null, and empty
string will all be treated as falsy.
Refs [UICHKOUT-792](https://issues.folio.org/browse/UICHKOUT-792)
> UICHKOUT-792 when formatting names, handle falsy values similarly

- CHANGELOG.md
- package.json
Add version 12.0 to the list of supported inventory interface versions.
DELETE /inventory/instances and DELETE /inventory/items have been deleting all records.
MODINV-731 changed them to delete records by CQL, this requires a major interface version bump.
ui-checkout doesn't need any code change because it doesn't use these two DELETE APIs.
> UICHKOUT-800: Support inventory 12.0 in okapiInterfaces

- CHANGELOG.md
- package.json
Bump major versions of several @folio/stripes-* packages.
[UICHKOUT-818](https://issues.folio.org/browse/UICHKOUT-818)
> UICHKOUT-818: bump stripes to 8.0.0 for Orchid/2023-R1

- CHANGELOG.md
- package.json
- Refs https://issues.folio.org/browse/UICHKOUT-841.
- Remove unneeded `react-redux` dependency.
> UICHKOUT-841 Drop react-redux.

- CHANGELOG.md
- src/components/ScanFooter/ScanFooter.js
- src/components/ScanFooter/ScanFooter.test.js
UI tests replacement with RTL/Jest for src/components/ScanFooter/ScanFooter.js
[UICHKOUT-834](https://issues.folio.org/browse/UICHKOUT-834)
> UICHKOUT-834: UI tests replacement with RTL/Jest for src/components/ScanFooter/ScanFooter.js

- CHANGELOG.md
- src/components/NotificationModal/NotificationModal.js
- src/components/NotificationModal/NotificationModal.test.js
- src/util.js
- src/util.test.js
- test/jest/__mock__/stripesComponents.mock.js
- Use camel case notation for all data-testid
- Remove magic strings for testIds and labelIds
https://issues.folio.org/browse/UICHKOUT-848
> UICHKOUT-848: Use camel case notation for all data-testid

- CHANGELOG.md
- package.json
Update @folio/circulation to 8.0.1
https://issues.folio.org/browse/UICHKOUT-849
This pull request depends on https://github.com/folio-org/ui-circulation/pull/1009
After merge https://github.com/folio-org/ui-circulation/pull/1009 we will ralease ui-circulation with version 8.0.1
> UICHKOUT-849: Update @folio/circulation to 8.0.1

- CHANGELOG.md
- src/util.js
- src/util.test.js
Use == instead of = for CQL service point filtering.
[UICHKOUT-853](https://issues.folio.org/browse/UICHKOUT-853)
> UICHKOUT-853: Requests search is using CQL with = for service point filtering

- CHANGELOG.md
- package.json
- test/jest/babel.config.js
Upgrade babel config
Pulling the babel config directly from stripes-webpack via stripes-cli, in order to guarantee the babel plugins, versions, and config are all aligned.
https://issues.folio.org/browse/UICHKOUT-861
> UICHKOUT-861: Upgrade babel config

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
Update Node.js to v18 in GitHub Actions
https://issues.folio.org/browse/UICHKOUT-862
> UICHKOUT-862: Update Node.js to v18 in GitHub Actions

- CHANGELOG.md
- src/ModalManager.js
- src/ModalManager.test.js
Cover ModalManager by jest/RTL tests
[UICHKOUT-821](https://issues.folio.org/browse/UICHKOUT-821)
> UICHKOUT-821: UI tests replacement with RTL/Jest for src/ModalManager.js

- CHANGELOG.md
- src/components/ViewItem/ViewItem.js
- src/components/ViewItem/ViewItem.test.js
- src/constants.js
- src/util.js
- src/util.test.js
When a DCB item is checked out, the scanned item should not have "Item details" in its Action menu.
When the item that is checkedout is a DCB item, meaning it has instance id and holdings record id as DCB_INSTANCE_ID and DCB_HOLDINGS_RECORD_ID, then the Action menu of the scanned item will not have "Item details" menu item.
[UICHKOUT-871](https://issues.folio.org/browse/UICHKOUT-871) - [DCB] Check-out: Hide Item details in Actions menu (Borrowing/ Pickup library)
- Do JIRAs …
> UICHKOUT-871 - Hide 'Item details' in Action menu when item is virtual.

- CHANGELOG.md
- src/components/ViewItem/ViewItem.js
- src/components/ViewItem/ViewItem.test.js
- src/constants.js
- src/util.js
- src/util.test.js
[DCB] Check-out: Hide Item details, patron/staff info in Actions menu (Pickup library)
When the borrower is a DCB patron, "Add patron info" and "Add staff info" items in scanned item Action menu are hidden.
[UICHKOUT-872](https://issues.folio.org/browse/UICHKOUT-872)
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
> UICHKOUT-872 - Hide Patron and Staff Info in Action menu when DCB patron.

- CHANGELOG.md
- src/components/OverrideModal/OverrideModal.js
- src/components/OverrideModal/OverrideModal.test.js
- src/components/ViewItem/AddInfoDialog.js
- src/components/ViewItem/AddInfoDialog.test.js
- translations/ui-checkout/en.json
https://folio-org.atlassian.net/browse/UICHKOUT-887
We removed local translation key and replace it with global one `stripes-components.saveAndClose`
> UICHKOUT-887: Use Save & close button label stripes-component translation key

- CHANGELOG.md
- src/components/ViewItem/ViewItem.js
Fix headings words breaking on checkout table.
I use fixed width for each column instead of percentages (approach approved by PO). 
[UICHKOUT-886](https://folio-org.atlassian.net/browse/UICHKOUT-886)
> UICHKOUT-886: Break long words in headings

- CHANGELOG.md
- package.json
Update ui-plugin-create-inventory-records to version 5.0.0
https://issues.folio.org/browse/UICHKOUT-925
> UICHKOUT-925: Update ui-plugin-create-inventory-records to version 5.0.0

- CHANGELOG.md
- package.json
- src/components/ErrorModal/ErrorModal.js
- src/components/ErrorModal/ErrorModal.test.js
- src/components/PatronBlock/PatronBlockModal.js
- src/components/ViewItem/ViewItem.js
- src/components/ViewItem/ViewItem.test.js
- test/jest/__mock__/stripes.mock.js
- test/jest/__mock__/stripesCore.mock.js
[UICHKOUT-927](https://folio-org.atlassian.net/browse/UICHKOUT-927) - Update permission checks of ui-users
Several permissions of module ui-users have been updated in the scope of [UIU-3214](https://folio-org.atlassian.net/browse/UIU-3214)
ui-checkout module leverages various ui-users permissions in order to conditionally render several buttons, menu items…
Below is the list, where some refactor is needed for the permission checks-
[ui-checkout/src/components/ViewItem/ViewItem.js at ed73f74a2fadac70e0b321f7d9f491cf5de9e047 · folio-org/ui-checkout](https://github.com/folio-org/ui-checkout/blob/ed73f74a2fadac70e0b321f7d9f491cf5de9e047/src/components/ViewItem/ViewItem.js#L373) 
[ui-checkout/src/components/ViewItem/ViewItem.js at ed73f74a2fadac70e0b321f7d9f491cf5de9e047 · …
> UICHKOUT-927 - Update permission checks of ui-users

- CHANGELOG.md
- package.json
- src/CheckOut.js
Update permission after mod-patron-blocks permission changes
https://issues.folio.org/browse/UICHKOUT-930
> UICHKOUT-930: Update permission after mod-patron-blocks permission changes

- CHANGELOG.md
- src/components/UserDetail/UserDetail.css
- src/components/UserDetail/UserDetail.js
- src/util.js
- src/util.test.js
Previously, `getFullName()` would include trailing whitespace if the given object did not include a `personal.middleName` property. Now, all output is trimmed.
Refs [UICHKOUT-941](https://folio-org.atlassian.net/browse/UICHKOUT-941)
> UICHKOUT-941 omit trailing whitespace from getFullName()

- CHANGELOG.md
- src/CheckOut.test.js
Some jest related packages have dependency on nwsapi package. 
Due to that dependency we can not correctly mock callback passed to addEventListener.
[UICHKOUT-955](https://folio-org.atlassian.net/browse/UICHKOUT-955)
> UICHKOUT-955: Remove failed tests after packages updating

- CHANGELOG.md
- package.json
Add missed subpermission.
[UICHKOUT-956](https://folio-org.atlassian.net/browse/UICHKOUT-956)
> UICHKOUT-956: Modal with error appears if user has "Check out: All permissions" permission

- CHANGELOG.md
- src/ModalManager.js
When running in dev mode — and not in production — React 18 will deliberately run all `componentDidMount` methods twice. It does this to help you find places where you are inadvertently doing non-idempotent things, such as, well, checking out items. See https://react.dev/reference/react/Component#componentdidmount
The proper fix is to change the whole approach of ui-checkout so it doesn’t rely on side-effects of mounting a component. That would be a complicated job and I don’t understand the logic of the module well enough to confident I was doing that work right.
This commit simply adds guard code to the `componentDidMount` method so that it only runs once. That makes no difference to how the code runs in production, but makes it possible to do development.
> [UICHKOUT-967] Guard against multiple invocations of componentDidMount

- src/components/ItemForm/ItemForm.js
`barcode` may not be defined when the app first renders, and therefore cannot be required.
> UICHKOUT-975 proptypes correction
