folio-org/ui-checkout

package.json
=> Add settings.checkout.enabled permissionSet to package.json.

CHANGELOG.md, settings/ScanCheckoutSettings.js
Prepares for next version of mod-configuration
=> Remove 'metadata' property from JSON before PUTting. UICHKOUT-15

Scan.js, lib/ProxyForm/ProxyForm.js, lib/ViewPatron/ViewPatron.js
This PR introduces couple changes based on the feedback in UICHKOUT-5.
=> Update proxy modal. Fixes UICHKOUT-5.

CHANGELOG.md, Scan.js, index.js, lib/ItemForm/ItemForm.js, lib/ProxyForm/ProxyForm.js, lib/UserDetail/UserDetail.js, lib/ViewItem/ViewItem.js, lib/ViewPatron/ViewPatron.js
Use PropTypes, not React.PropTypes.
=> Stripes 427 proptypes

package.json
=> Remove duplicate `settings.loan-policies.all` permission

Scan.js
This PR refactors `Scan.js` and uses new `accumulate` and `GET` from `stripes-connect`. The `isomorphic-fetch` is gone.
=> Refactor checkout to use pure stripes-connect. Fixes UICHKOUT-21

package.json
=> Add "optionalDependencies" for ui-plugin-find-user

CHANGELOG.md, lib/PatronForm/PatronForm.js
Fixes [UICHKOUT-50](https://issues.folio.org/projects/UICHKOUT/issues/UICHKOUT-50).
=> Don't bind non-existant function. Fixes UICHKOUT-50

CHANGELOG.md, lib/UserDetail/UserDetail.js
[STRIPES-482](https://issues.folio.org/browse/STRIPES-482)
=> favor Link over href. Refs STRIPES-482

CHANGELOG.md, package.json
Refs [STRIPES-501](https://issues.folio.org/browse/STRIPES-501), [STRIPES-490](https://issues.folio.org/browse/STRIPES-490).
=> updating dependencies. Refs STRIPES-501, STRIPES-490

CHANGELOG.md, Scan.js, lib/ItemForm/ItemForm.js, lib/ScanTotal/ScanTotal.js
Fixes https://issues.folio.org/browse/UICHKOUT-57.
=> Display end session button when a patron has been selected. Fixes UICHKOUT-57

CHANGELOG.md, lib/ViewItem/ViewItem.js
Fixes [UICHKOUT-48](https://issues.folio.org/browse/UICHKOUT-48).
=> Rewire links from items to inventory. Fixes UICHKOUT-48

test/ui-testing/error_messages.js
Makes test pass when run in browser on this developers machine
=> Add wait to let form fully load before entering data. UITEST-16

constants.js, lib/PatronForm/PatronForm.js, test/ui-testing/error_messages.js
[https://issues.folio.org/browse/UICHKOUT-49](https://issues.folio.org/browse/UICHKOUT-49)
=> Cleanup labels. Part of UICHKOUT-49

CHANGELOG.md, Scan.js, lib/ProxyForm/ProxyForm.css, lib/ProxyForm/ProxyForm.js, lib/ViewPatron/ViewPatron.js, util.js
Fixes [https://issues.folio.org/browse/UICHKOUT-53](https://issues.folio.org/browse/UICHKOUT-53)
=> Prevent expired sponsors and expired proxy relationships from being selected. Fixes UICHKOUT-53

CHANGELOG.md, Scan.js, ScanItems.js, constants.js, lib/ErrorModal/ErrorModal.js, lib/ErrorModal/index.js, lib/ItemForm/ItemForm.js, lib/PatronForm/PatronForm.js, lib/ProxyForm/ProxyForm.js, util.js
Fixes [UICHKOUT-66](https://issues.folio.org/browse/UICHKOUT-66)
=> Get fixed loan period from loan policy. Fixes UICHKOUT-66.

CHANGELOG.md, lib/ViewItem/ViewItem.js
Fixes [https://issues.folio.org/browse/UICHKOUT-74](https://issues.folio.org/browse/UICHKOUT-74).
=> Adjust action menu. Fixes UICHKOUT-74

CHANGELOG.md, lib/UserDetail/UserDetail.js, lib/ViewPatron/ViewPatron.js, package.json
Fixes [UICHKOUT-47](https://issues.folio.org/browse/UICHKOUT-47).
=> Make borrowing patron more prominent. Fixes UICHKOUT-47

lib/PatronForm/PatronForm.js, util.js
[https://issues.folio.org/browse/UICHKOUT-66](https://issues.folio.org/browse/UICHKOUT-66)
=> Adjust due date calculation. Part of UICHKOUT-66

ScanItems.js
[https://issues.folio.org/browse/UICHKOUT-66](https://issues.folio.org/browse/UICHKOUT-66)
=> Fix validation for fixed loan period. Part of UICHKOUT-66

CHANGELOG.md, Scan.js, util.js
Refs [https://issues.folio.org/browse/UICIRC-47](https://issues.folio.org/browse/UICIRC-47).
=> Refactor checkout settings. Refs UICIRC-47.

ScanItems.js, lib/ViewItem/ViewItem.js, loanUtil.js, util.js
[https://issues.folio.org/browse/UICHKOUT-66](https://issues.folio.org/browse/UICHKOUT-66)
=> Fix dueDate Calculation. Part of UICHKOUT-66

Scan.js, ScanItems.js
Fixes [UICHKOUT-409](https://issues.folio.org/browse/UICHKOUT-409)
=> replace missing translation key. Refs UICHKOUT-75, UICHKOUT-409

Scan.js
Refs [UICHKOUT-409](https://issues.folio.org/browse/UICHKOUT-409)
=> Use correct translation key for items pane. Refs UICHKOUT-409

CHANGELOG.md, constants.js, loanUtil.js
[https://issues.folio.org/browse/UICHKOUT-408](https://issues.folio.org/browse/UICHKOUT-408)
=> Fix rolling loans due date calculation. Fixes UICHKOUT-408.

CHANGELOG.md, constants.js
[https://issues.folio.org/browse/UICIRC-53](https://issues.folio.org/browse/UICIRC-53)
=> * Match interval period values with the values on the server. Refs UICIRC-53.

constants.js, loanUtil.js
https://issues.folio.org/browse/UICIRC-53
=> Match periodId and profileId values with the values on the server. Refs UICIRC-53.

CHANGELOG.md, ScanItems.js
https://issues.folio.org/browse/UICHKOUT-413
=> Fix params being sent to apply endpoint. Fixes UICHKOUT-413.

CHANGELOG.md, ScanItems.js
https://issues.folio.org/browse/UICHKOUT-410
=> Show error when trying to check out item that has been requested. Fixes UICHKOUT-410.

CHANGELOG.md, Scan.js, lib/PatronForm/PatronForm.js
To avoid reference to null object in patron form componentWillMount
=> Initialize patron object to empty rather than null. UICHKOUT-418

ScanItems.js, lib/ItemForm/ItemForm.js, test/ui-testing/settings.js
=> Uichkout 421 focus cursor

CHANGELOG.md, lib/ViewItem/ViewItem.js
https://issues.folio.org/browse/UICHKOUT-423
=> Adjust columns width on the checkout screen. Fixes UICHKOUT-423.

README.md, ScanItems.js, lib/ItemForm/ItemForm.js, lib/PatronForm/PatronForm.js
Reverts folio-org/ui-checkout#125
=> Revert "fix ref to TextField"

lib/ItemForm/ItemForm.js, lib/PatronForm/PatronForm.js
I used componentDidMount in place of componentWillUpdate, but it didn't work. Temporarily using UNSAFE_componentWillUpdate and while I look at replacing it.
=> temporarily use unsafe method

lib/ItemForm/ItemForm.js, lib/PatronForm/PatronForm.js
=> UNSAFE_componentWillUpdate -> componentDidUpdate

CHANGELOG.md, ScanItems.js
https://issues.folio.org/browse/UICHKOUT-429
=> Fix checkout sounds. Fixes UICHKOUT-429

CHANGELOG.md, Scan.js, ScanItems.js, lib/ItemForm/ItemForm.js, lib/PatronForm/PatronForm.js, lib/UserDetail/UserDetail.js
Fix input focus issues https://issues.folio.org/browse/UICHKOUT-432
Make lint happy
=> Fix input focus issues. Fixes UICHKOUT-432

Scan.js, ScanItems.js, index.js, lib/ErrorModal/ErrorModal.js, lib/ItemForm/ItemForm.js, lib/PatronForm/PatronForm.js, lib/ScanFooter/ScanFooter.js, lib/ScanTotal/ScanTotal.js, lib/UserDetail/UserDetail.js, lib/ViewItem/ViewItem.js, lib/ViewPatron/ViewPatron.js
https://issues.folio.org/browse/STCOR-208
Context API was unnecessary. I passed down `translate` in `props`; the component tree is not that deep.
=> STCOR-208: remove old context api

lib/ErrorModal/ErrorModal.js, translations/ui-checkout/en.json
https://issues.folio.org/browse/UICHKOUT-406
=> Rename button on error modal. Part of UICHKOUT-406

index.js, lib/ItemForm/ItemForm.js, lib/PatronForm/PatronForm.js, lib/ScanTotal/ScanTotal.js, lib/ViewItem/ViewItem.js, package.json
Removes unnecessary `babel` packages, adds needed `devDependencies`, and uses the latest `eslint-config-stripes`.
=> Clean up dependencies

package.json
=> Uichkout 443 release 1.2.0

lib/PatronForm/PatronForm.js, package.json
https://issues.folio.org/browse/STCOM-331
=> STCOM-331 Get Pluggable from stripes-core

test/ui-testing/error_messages.js
Manipulating the checkboxes for Settings > Circulation > Other settings
is a longstanding source of trouble. JUST USE THE HELPER THAT DOES IT
THE RIGHT WAY.
Refs [UITEST-55](https://issues.folio.org/browse/UITEST-55)
=> srsly do not change your own checkout settings

CHANGELOG.md, src/components/PatronForm/PatronForm.js
Refs [STCOM-385](https://issues.folio.org/browse/STCOM-385)
=> show `active` column in find-user popup

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/es.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/pt_BR.json
=> Update translation strings as of 20181031T224505

translations/ui-checkout/pt_BR.json
=> Update translation strings as of 20181110T181812

src/components/PatronForm/PatronForm.js
Follow-up from https://github.com/folio-org/ui-checkout/pull/201
=> Remove unnecessary intl prop

src/components/PatronForm/PatronForm.js
https://issues.folio.org/browse/STSMACOM-146
=> Fix user lookup setup. Part of STSMACOM-146

CHANGELOG.md, src/Scan.js, src/ScanItems.js, src/components/ErrorModal/ErrorModal.js, src/components/ItemForm/ItemForm.js, src/components/PatronForm/PatronForm.js, src/components/ScanFooter/ScanFooter.js, src/components/ScanTotal/ScanTotal.js, src/components/UserDetail/UserDetail.js, src/components/ViewItem/ViewItem.js, src/components/ViewPatron/ViewPatron.js, src/index.js, translations/ui-checkout/en.json
According to [UICHKOUT 458](https://issues.folio.org/browse/UICHKOUT-458) all hardcoded strings should be internationalized using the react-intl pattern constructs outlined [here](https://github.com/folio-org/stripes/blob/master/doc/i18n.md).
=> UICHKOUT 458: Apply internationalization to all hardcoded strings

CHANGELOG.md, src/Scan.js, src/ScanItems.js, src/components/PatronBlock/PatronBlock.css, src/components/PatronBlock/PatronBlock.js, src/components/PatronBlock/PatronBlockModal.js, src/components/PatronBlock/index.js, src/components/ViewPatron/ViewPatron.js, translations/ui-checkout/en.json
We are adding:
* Feature "Enforce manual patron blocks". Refs [UIU-675](https://issues.folio.org/browse/UIU-675).
=> Add feature fees/fines

translations/ui-checkout/en.json
https://issues.folio.org/browse/UICHKOUT-467
=> Fix loan action menu labels. Fixes UICHKOUT-467

CHANGELOG.md, package.json, src/components/ViewItem/ViewItem.js
https://issues.folio.org/browse/UICHKOUT-457
=> Adjust checkout columns width. Fixes UICHKOUT-457.

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20190113T223639

src/CheckOut.js, src/ScanItems.js, src/components/ItemForm/ItemForm.js, src/components/ViewPatron/ViewPatron.js
Fix props. Ref [UICHKOUT-33](https://issues.folio.org/browse/UICHKOUT-33).
=> Fix Fees/Fines

package.json
https://github.com/folio-org/ui-checkout/compare/UICIRC-164
=> Update circulation interface to 6.0. Part of UICIRC-164

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20190321T130117

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20190403T132033

src/components/ViewItem/ViewItem.js
https://issues.folio.org/browse/UICIRC-197
=> Keep loan policy visible after due date change. Fixes UICIRC-197

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20190405T144349

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20190415T231934

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_419.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20190426T133506

translations/ui-checkout/es_ES.json, translations/ui-checkout/pt_BR.json
=> Update translation strings as of 20190429T154045

src/components/ViewItem/ViewItem.js, test/bigtest/interactors/check-out.js, test/bigtest/tests/check-out-test.js
=> UICHKOUT-498: Fix items sort direction.

translations/ui-checkout/ar.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20190502T124851

src/ScanItems.js, src/components/ErrorModal/ErrorModal.js, src/components/ItemForm/ItemForm.js, src/components/OverrideModal/OverrideModal.js
This is an initial work related to modal refactoring needed by UICHKOUT-493. I would like to merge this first before continuing further.
=> Init work on modal refactoring. Part of UICHKOUT-493

translations/ui-checkout/ar.json
=> Update translation strings as of 20190528T121921

src/ModalManager.js, test/bigtest/tests/check-out-test.js
https://issues.folio.org/browse/UICHKOUT-493
=> Flip order of modals. Part of UICHKOUT-493.

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_419.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20190609T200038

src/CheckOut.js, src/components/PatronForm/PatronForm.js
Change initially focused component
https://issues.folio.org/browse/UICHKOUT-508
=> UICHKOUT-508 - Check out App | Accessibility | Focus is on the wrong box

CHANGELOG.md, package.json
Fixes [UIU-1078](https://issues.folio.org/browse/UIU-1078)
=> add missing permission to checkout-all pset

src/components/MultipieceModal/MultipieceModal.js
https://issues.folio.org/browse/UICHKOUT-527
=> Fix missing pieces description. Fixes UICHKOUT-527

translations/ui-checkout/de.json
=> Update translation strings as of 20190718T013203

src/ModalManager.js, test/bigtest/tests/check-out-test.js, translations/ui-checkout/en.json
- to add date and source fields for checkout notes
https://issues.folio.org/browse/UICHKOUT-496
=> UICHKOUT-496 - Link to check out notes in action menu (with date, source)

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_419.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20190807T131714

CHANGELOG.md, test/bigtest/interactors/check-out.js
Handle broken tests which caused be a recent [update](https://github.com/folio-org/stripes-components/pull/1011) of _MultiColumnList_ component. Refs [UICHKOUT-538](https://issues.folio.org/browse/UICHKOUT-538).
=> UICHKOUT-538: Handle broken tests

CHANGELOG.md, package.json
Release module for the FOLIO 2019Q3.2. Refs [UICHKOUT-539](https://issues.folio.org/browse/UICHKOUT-539).
=> Release v1.11.0

package.json
Restores #380 by reverting folio-org/ui-checkout#385
=> Restore "UICHKOUT-543: Update the circulation API to support changes in the rule editor"

translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20191022T162142

src/components/MultipieceModal/MultipieceModal.js, src/components/PatronBlock/PatronBlockModal.js
Clean a few React warnings about missing `key` attributes, spurious
method handlers, etc.
=> minor markup cleanup

src/CheckOut.js
https://issues.folio.org/browse/UICHKOUT-556
=> UICHKOUT-556: Add end session on patron look up.

translations/ui-checkout/ru.json
=> Update translation strings as of 20191104T173556

translations/ui-checkout/it_IT.json
=> Update translation strings as of 20191112T144117

src/CheckOut.js, test/bigtest/tests/check-out-test.js
When checking in a delivery item with status 'Awaiting delivery', a user has the ability to automatically check out this item.
* After checking in a delivery item, the check-in app redirects the user to the checkout app and passes the user and item barcodes to the location state
* Chech out app checks if the location state contains this data. If it does, then the forms are populated with those values and submitted
=> UICHKIN-109: implement automatic check out after item check in

src/CheckOut.js
To call end session endpoint only in case when End Session button is clicked
https://issues.folio.org/browse/UICHKOUT-560
=> UICHKOUT-560 - UI calls end session endpoint several times

CHANGELOG.md, src/components/UserDetail/UserDetail.js
Include New "Open - Awaiting delivery" Status When Accessing Request Queue from Check Out App
https://issues.folio.org/browse/UICHKOUT-563
=> UICHKOUT-563: Include new 'Open - Awaiting delivery'

translations/ui-checkout/fr_FR.json
=> Update translation strings as of 20191209T142332

translations/ui-checkout/ar.json
=> Update translation strings as of 20200106T223901

CHANGELOG.md, src/components/ViewItem/ViewItem.js, translations/ui-checkout/en.json
- replace uncontrolled dropdown component
- add tooltip for actions dropdown
https://issues.folio.org/browse/UICHKOUT-558
=> UICHKOUT-558 - Make the Check out ellipsis accessible

CHANGELOG.md, package.json
https://issues.folio.org/browse/UICHKOUT-585
=> UICHKOUT-585: Update okapi interfaces.

translations/ui-checkout/fr_FR.json
=> Update translation strings as of 20200302T163727

test/ui-testing/error-messages.js
`diku` is a user with an invalid user record (it's incomplete, missing
the `personal` object) that seems to be created by ... some unknown part
of somebody's process somewhere. It's a bit of a mystery. At any rate,
selecting this user causes all kinds of grief because the record is
invalid in ways that are normally protected against (i.e. if it's
impossible to create a record without a `personal` attribute, then we
don't have to check for its presence because such presence is
guaranteed) except here we are.
=> avoid accidentally selecting diku

CHANGELOG.md, src/ModalManager.js, src/ScanItems.js, src/components/ViewItem/ViewItem.js
https://issues.folio.org/browse/UICHKOUT-597
=> UICHKOUT-597: Fix bugs in view checkout notes & change due date

translations/ui-checkout/ru.json
=> Update translation strings as of 20200312T133304

CHANGELOG.md, src/components/PatronBlock/PatronBlock.css, src/components/UserDetail/UserDetail.css, src/components/ViewPatron/ViewPatron.css, test/bigtest/interactors/check-out.js, test/bigtest/tests/check-out-test.js
Change selected parton background color to increase color contrast.
https://issues.folio.org/browse/UICHKOUT-603
**Before**
**After**
=> UICHKOUT-603: Change bg color

src/CheckOut.js
Clear inactivity timer after session ends.
https://issues.folio.org/browse/UICHKOUT-607
=> UICHKOUT-607 - Three identical e-mail notices for one checkout

translations/ui-checkout/ja.json
=> Update translation strings as of 20200409T134057

test/bigtest/interactors/check-out.js, test/bigtest/tests/check-out-test.js
Unit tests were recently updated on master; this PR brings those changes
to the release branch. They reflect underlying DOM changes, not actual
functional changes.
=> patch unit tests

translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20200413T183215

src/CheckOut.js
Update conditions for timer initialization and removing
https://issues.folio.org/browse/UICHKOUT-607
=> UICHKOUT-607 - Identical e-mail notices for one checkout

translations/ui-checkout/ja.json
=> Update translation strings as of 20200421T180634

src/CheckOut.js
* Clean up patronId from activeRecord in case when session was closed
* Clean up time issues related to init/removal, session-end, and app-switching
=> UICHKOUT-607 multiple notices sent for a single checkout

package.json, src/CheckOut.js, src/ScanItems.js, src/components/ErrorModal/ErrorModal.js, src/components/ItemForm/ItemForm.js, src/components/OverrideModal/OverrideModal.js, src/components/PatronForm/PatronForm.css, src/components/PatronForm/PatronForm.js, test/bigtest/interactors/check-out.js
Migrate module from redux-form to react-final form.
https://issues.folio.org/browse/UICHKOUT-593
=> UICHKOUT-593 - Refactor forms to use final-form

translations/ui-checkout/ru.json
=> Update translation strings as of 20200602T151309

CHANGELOG.md, translations/ui-checkout/en.json
Refs [UICHKOUT-629](https://issues.folio.org/browse/UICHKOUT-629)
=> UICHKOUT-629 make permissions localizable

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_419.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/he.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/ja.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/ru.json, translations/ui-checkout/ur.json, translations/ui-checkout/zh_CN.json, translations/ui-checkout/zh_TW.json
=> Update translation strings as of 20200615T161518

translations/ui-checkout/ru.json
=> Update translation strings as of 20200615T202100

translations/ui-checkout/ru.json
=> Update translation strings as of 20200701T150841

CHANGELOG.md, karma.conf.js, test/bigtest/helpers/monkey-patch-run.js, test/bigtest/helpers/setup-application.js, test/bigtest/index.js, test/bigtest/interactors/check-out.js, test/bigtest/interactors/proxy-modal.js, test/bigtest/tests/check-out-test.js
https://issues.folio.org/browse/UICHKOUT-533
=> UICHKOUT-533: Create BigTest tests for patron lookup widget

translations/ui-checkout/pt_BR.json
=> Update translation strings as of 20200707T213422

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_419.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/he.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/ja.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/ru.json, translations/ui-checkout/ur.json, translations/ui-checkout/zh_CN.json, translations/ui-checkout/zh_TW.json
=> Update translation strings as of 20200710T132222

CHANGELOG.md, src/ScanItems.js
This is me following up on a request to refactor the code for
my previous solution to this issue.  I was unable to do this
at the time because of scheduling and issues with my development
environment.
Refs: https://issues.folio.org/browse/UICHKOUT-639
=> UICHKOUT-639: Proxy borrower does not display on loan details

translations/ui-checkout/ar.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/pt_BR.json
=> Update translation strings as of 20200716T140311

CHANGELOG.md, test/bigtest/constants.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/manualPatronBlocks.js, test/bigtest/tests/patron-block-test.js
Increase test coverage for patron blocks
https://issues.folio.org/browse/UICHKOUT-531
**Before**
**After**
=> UICHKOUT-531: Add tests for automated patron blocks

test/bigtest/network/scenarios/sessionTimeout.js, test/bigtest/tests/session-test.js
To increase test coverage for automated end-session, I removed back commented tests.
https://issues.folio.org/browse/UICHKOUT-532
**Before**
**After**
=> UICHKOUT-532: Tests for session timeout

translations/ui-checkout/zh_CN.json
=> Update translation strings as of 20200727T130814

CHANGELOG.md, package.json, src/CheckOut.js, src/components/ItemForm/ItemForm.js, src/components/PatronForm/PatronForm.js, src/components/ScanTotal/ScanTotal.js, test/bigtest/interactors/check-out.js, test/bigtest/tests/check-out-test.js
https://issues.folio.org/browse/UICHKOUT-628
Create access to New fast add record template from Check out screen.
Add some changes to the design of the buttons.
=> UICHKOUT-628: Create New fast add record via Check out

translations/ui-checkout/it_IT.json
=> Update translation strings as of 20200824T140725

translations/ui-checkout/ja.json
=> Update translation strings as of 20200914T140557

translations/ui-checkout/ar.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_419.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/he.json, translations/ui-checkout/hi_IN.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/ja.json, translations/ui-checkout/ko.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/ru.json, translations/ui-checkout/ur.json, translations/ui-checkout/zh_CN.json, translations/ui-checkout/zh_TW.json
=> Update translation strings as of 20200922T125348

translations/ui-checkout/ja.json
=> Update translation strings as of 20201007T133333

translations/ui-checkout/es.json, translations/ui-checkout/es_419.json, translations/ui-checkout/es_ES.json
=> Update translation strings as of 20201016T144229

translations/ui-checkout/ar.json, translations/ui-checkout/ber.json, translations/ui-checkout/ca.json, translations/ui-checkout/da.json, translations/ui-checkout/de.json, translations/ui-checkout/en_GB.json, translations/ui-checkout/en_SE.json, translations/ui-checkout/en_US.json, translations/ui-checkout/es.json, translations/ui-checkout/es_419.json, translations/ui-checkout/es_ES.json, translations/ui-checkout/fr.json, translations/ui-checkout/fr_FR.json, translations/ui-checkout/he.json, translations/ui-checkout/hi_IN.json, translations/ui-checkout/hu.json, translations/ui-checkout/it_IT.json, translations/ui-checkout/ja.json, translations/ui-checkout/ko.json, translations/ui-checkout/pl.json, translations/ui-checkout/pt_BR.json, translations/ui-checkout/pt_PT.json, translations/ui-checkout/ru.json, translations/ui-checkout/ur.json, translations/ui-checkout/zh_CN.json, translations/ui-checkout/zh_TW.json
=> Update translation strings as of 20201119T214636

CHANGELOG.md, src/components/ViewItem/ViewItem.js, translations/ui-checkout/en.json, translations/ui-checkout/en_US.json
https://issues.folio.org/browse/UICHKOUT-675
Pull in the correct translation string.
=> UICHKOUT-675: Fix label translation

.gitignore, CHANGELOG.md, src/CheckOut.js, src/components/PatronBlock/PatronBlock.css, src/components/PatronBlock/PatronBlock.js, src/components/ViewPatron/ViewPatron.css, src/components/ViewPatron/ViewPatron.js, test/bigtest/helpers/wait.js, test/bigtest/interactors/block-modal.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/manualPatronBlocks.js, test/bigtest/tests/modal-order-test.js
Proxy not allowed to check out items for sponsor if proxy has patron block. Patron block not displaying correctly when proxy checking out for blocked sponsor.
https://issues.folio.org/browse/UICHKOUT-673
https://issues.folio.org/browse/UICHKOUT-674
=> UICHKOUT-673: Patron block and blocked sponsor modal

CHANGELOG.md, package.json
Replace `all` perms with more fined grained permissions.
https://issues.folio.org/browse/UICHKOUT-724
=> UICHKOUT-724: Adjust ui-checkout.circulation permission set

src/CheckOut.js, src/ScanItems.js, src/components/PatronForm/PatronForm.js, test/bigtest/interactors/check-out.js, test/bigtest/tests/check-out-test.js
BigTest tests randomly fail for no reason. This PR is trying to address it. 
One issue I noticed is that async calls were not aborted correctly on unmount (after given test was finished) causing all sorts of issues when BigTest was moving from one test to another.
=> Fix checkout tests

CHANGELOG.md, package.json
https://issues.folio.org/browse/UICHKOUT-740
Increment stripes to v7, react to v17
=> UICHKOUT-740: Increment stripes to v7, react to v17

CHANGELOG.md, package.json
Support okapi interfaces `circulation` `12.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* The implementation of title level requests requires data migration to allow for a single queue of requests, whether item or title level (https://issues.folio.org/browse/UXPROD-3330).
https://issues.folio.org/browse/UICHKOUT-758
=> UICHKOUT-758: also support `circulation` `12.0`

CHANGELOG.md, package.json
Support okapi interfaces `circulation` `13.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* Was changed API associated with request queue.
https://issues.folio.org/browse/UICHKOUT-760
=> UICHKOUT-760: Also support circulation 13.0

CHANGELOG.md, src/components/SelectItemModal/SelectItemModal.js, translations/ui-checkout/en.json
1) Update Item list adding new such fields as : "Title" and "Call number"
2) The "List of items" header should be replaced with: "List of items: choose one"
=> UICHKOUT-763: Update Item List Modal Contents for Wildcard Item Lookup

CHANGELOG.md, src/CheckOut.js, src/components/SelectItemModal/SelectItemModal.js
Add id for Pane component.
https://issues.folio.org/browse/UICHKOUT-768
=> UICHKOUT-768: Add id for Pane component

CHANGELOG.md, PULL_REQUEST_TEMPLATE.md
- Add pull request template
https://issues.folio.org/browse/UICHKOUT-771
=> UICHKOUT-771: Add pull request template

CHANGELOG.md, package.json
Add circulation.end-patron-action-session.post sub permission to ui-checkout.circulation permissions list to get rid of unexpected issue after clicking on "End session" button. 
[UICHKOUT-775](https://issues.folio.org/browse/UICHKOUT-775)
=> Extend ui-checkout.circulation sub permissions

CHANGELOG.md, package.json, src/index.js
Remove react-hot-loader
https://issues.folio.org/browse/UICHKOUT-776
=> UICHKOUT-776: Remove react-hot-loader

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json
Refs [UICHKOUT-782](https://issues.folio.org/browse/UICHKOUT-782)
=> UICHKOUT-782 migrate CI to NodeJS v16

CHANGELOG.md, src/components/ErrorModal/ErrorModal.js, src/components/ItemForm/ItemForm.js, src/components/OverrideModal/OverrideModal.js, src/constants.js, src/util.js, test/bigtest/network/scenarios/errorsList.js, test/bigtest/network/scenarios/itemIsNotLoanable.js, test/bigtest/network/scenarios/outOfItemsLimit.js, test/bigtest/tests/override-patron-blocks-test.js, translations/ui-checkout/en.json
Use permanent error key instead of error message
https://issues.folio.org/browse/UICHKOUT-783
=> UICHKOUT-783: Use permanent error key instead of error message.

CHANGELOG.md, package.json
Release v8.1.0
https://issues.folio.org/browse/UICHKOUT-781
=> Release v8.1.0

CHANGELOG.md, src/components/MultipieceModal/MultipieceModal.js, src/components/PatronBlock/PatronBlock.js, src/components/UserDetail/UserDetail.js
Remove hardcoded empty values
https://issues.folio.org/browse/UICHKOUT-799
=> UICHKOUT-799: Remove hardcoded empty values

CHANGELOG.md, src/components/ViewItem/ViewItem.js
Fix Due date in Check out: Last number goes to the next line
https://issues.folio.org/browse/UICHKOUT-811
=> UICHKOUT-811: Fix Due date in Check out: Last number goes to the next line

src/components/ViewItem/ViewItem.css, src/components/ViewItem/ViewItem.js
Changes for the below tickets have been merged through PR https://github.com/folio-org/ui-checkout/pull/755
https://issues.folio.org/browse/UICHKOUT-806
https://issues.folio.org/browse/UICHKOUT-809
https://issues.folio.org/browse/UICHKOUT-810
This PR intends to correct the tooltip and icon rendering issue.
https://issues.folio.org/browse/UICHKOUT-809
https://issues.folio.org/browse/UICHKOUT-806
https://issues.folio.org/browse/UICHKOUT-810
- Do JIRAs exist to update the impacted …
=> UICHKOUT-809 - Visual indicator in checkout due date column for shortened loan period - part2

CHANGELOG.md, src/components/ViewItem/ViewItem.css, src/components/ViewItem/ViewItem.js, translations/ui-checkout/en.json
Checkout table usability improvements
As per the requirements of the ticket-
1. Made the checkout table (on the right) more responsive by introducing percentages.
2. Added a heading "Details" to the last actions column of the table.
https://issues.folio.org/browse/UICHKOUT-805
Checkout is not possible on development (mode) build (local host), as service points are not available. This is not the case with production (mode) build - checked this on folio snapshot and volaris rancher 1 and 2 too. Below are the supporting references.
Reference (local host):
checkout error -
Service points from user avatar click -
Service Points from user profile -
Is this a known issue? Any work arounds?
The issues/questions posted in above section were resolved after adding ui-servicepoints into the local …
=> UICHKOUT-805 - Checkout table usability improvements

CHANGELOG.md, src/components/ViewItem/ViewItem.js
Add screen reader accessibility to checkout flag
Added aria-label prop to Icon stripes component
https://issues.folio.org/browse/UICHKOUT-842
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
=> UICHKOUT-842 - Add screen reader accessibility to checkout flag

CHANGELOG.md, src/components/NotificationModal/NotificationModal.js, src/components/NotificationModal/NotificationModal.test.js, test/jest/__mock__/stripesComponents.mock.js
UICHKOUT-829: UI tests replacement with RTL/Jest for src/components/NotificationModal/NotificationModal.js
UI tests replacement with RTL/Jest
[UICHKOUT-829: UI tests replacement with RTL/Jest for src/components/NotificationModal/NotificationModal.js](https://issues.folio.org/browse/UICHKOUT-829)
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be …
=> UICHKOUT-829: UI tests replacement with RTL/Jest for src/components/NotificationModal/NotificationModal.js

CHANGELOG.md, src/constants.js, src/util.js, src/util.test.js
UI tests replacement with RTL/Jest for src/util.js
https://issues.folio.org/browse/UICHKOUT-824
=> UICHKOUT-824: UI tests replacement with RTL/Jest for src/util.js

CHANGELOG.md, src/index.js, src/index.test.js
UI tests replacement with RTL/Jest for src/index.js
https://issues.folio.org/browse/UICHKOUT-823
=> UICHKOUT-823: UI tests replacement with RTL/Jest for src/index.js

CHANGELOG.md, src/components/MultipieceModal/MultipieceModal.js, src/components/MultipieceModal/MultipieceModal.test.js, test/jest/__mock__/stripesComponents.mock.js
UI tests replacement with RTL/Jest for src/components/MultipieceModal/MultipieceModal.js
[UICHKOUT-828](https://issues.folio.org/browse/UICHKOUT-828)
=> UICHKOUT-828: UI tests replacement with RTL/Jest for src/components/MultipieceModal/MultipieceModal.js

CHANGELOG.md, package.json
=> UICHKOUT-844: R1 2023 Orchid module release 9.0.0

CHANGELOG.md, src/components/PatronBlock/PatronBlockModal.js, src/components/PatronBlock/PatronBlockModal.test.js, test/jest/__mock__/index.js, test/jest/__mock__/stripesCore.mock.js
UI tests replacement with RTL/Jest for src/components/PatronBlock/PatronBlockModal.js
[UICHKOUT-832](https://issues.folio.org/browse/UICHKOUT-832)
=> UICHKOUT-832: UI tests replacement with RTL/Jest for src/components/PatronBlock/PatronBlockModal.js

CHANGELOG.md, src/components/ScanTotal/ScanTotal.js, src/components/ScanTotal/ScanTotal.test.js
UI tests replacement with RTL/Jest for src/components/ScanTotal/ScanTotal.js
[UICHKOUT-835](https://issues.folio.org/browse/UICHKOUT-835)
=> UICHKOUT-835: UI tests replacement with RTL/Jest for src/components/ScanTotal/ScanTotal.js

CHANGELOG.md, src/components/PatronBlock/PatronBlock.js, src/components/PatronBlock/PatronBlock.test.js, test/jest/__mock__/index.js, test/jest/__mock__/reactRouterDom.mock.js, test/jest/__mock__/stripesComponents.mock.js
UI tests replacement with RTL/Jest for src/components/PatronBlock/PatronBlock.js
https://issues.folio.org/browse/UICHKOUT-831
=> UICHKOUT-831: UI tests replacement with RTL/Jest for src/components/PatronBlock/PatronBlock.js

CHANGELOG.md, src/components/SelectItemModal/SelectItemModal.js, src/components/SelectItemModal/SelectItemModal.test.js, test/jest/__mock__/stripesComponents.mock.js
UI tests replacement with RTL/Jest for src/components/SelectItemModal/SelectItemModal.js
[UICHKOUT-836](https://issues.folio.org/browse/UICHKOUT-836)
=> UICHKOUT-836: UI tests replacement with RTL/Jest for src/components/SelectItemModal/SelectItemModal.js

CHANGELOG.md, src/components/UserDetail/Loans.js, src/components/UserDetail/Loans.test.js, test/jest/__mock__/intl.mock.js, test/jest/__mock__/reactRouterDom.mock.js
UI tests replacement with RTL/Jest for src/components/UserDetail/Loans.js
https://issues.folio.org/browse/UICHKOUT-837
100% coverage
=> UICHKOUT-837: UI tests replacement with RTL/Jest for src/components/UserDetail/Loans.js

CHANGELOG.md
Update CHANGELOG after release
https://issues.folio.org/browse/UICHKOUT-852
=> UICHKOUT-852: Update CHANGELOG after release

CHANGELOG.md, src/CheckOut.js, src/ScanItems.js, src/constants.js
Reassign limit variable from hardcoded value to MAX_RECORDS constant for CheckOut.js
https://issues.folio.org/browse/UICHKOUT-850
=> UICHKOUT-850: Reassign limit variable from hardcoded value to MAX_RECORDS constant for CheckOut.js

CHANGELOG.md, src/components/UserDetail/UserDetail.js
Reassign limit variable from hardcoded value to MAX_RECORDS constant for UserDetail.js
https://issues.folio.org/browse/UICHKOUT-851
Should be merged after https://github.com/folio-org/ui-checkout/pull/790
=> UICHKOUT-851: Reassign limit variable from hardcoded value to MAX_RECORDS constant for UserDetail.js

CHANGELOG.md, src/components/UserDetail/Loans.js, src/components/UserDetail/Loans.test.js
If the user has fines, they can click the fine amount as a link and have it open the fine information in the Users app
https://issues.folio.org/browse/UICHKOUT-802
=> UICHKOUT-802: If the user has fines, they can click the fine amount as a link and have it open the fine information in the Users app

CHANGELOG.md, src/components/UserDetail/UserDetails.test.js, test/jest/__mock__/stripesComponents.mock.js
Cover UserDetail.js file by RTL/Jest tests.
[UICHKOUT-838](https://issues.folio.org/browse/UICHKOUT-838)
=> UICHKOUT-838: UI tests replacement with RTL/Jest for src/components/UserDetail/UserDetail.js

CHANGELOG.md, src/components/ViewPatron/ViewPatron.test.js, test/jest/__mock__/stripesComponents.mock.js, test/jest/__mock__/stripesSmartComponents.mock.js
Cover ViewPatron by RTL/Jest tests.
[UICHKOUT-840](https://issues.folio.org/browse/UICHKOUT-840)
=> UICHKOUT-840: UI tests replacement with RTL/Jest for src/components/ViewPatron/ViewPatron.js

CHANGELOG.md, package.json, src/ScanItems.js, test/jest/babel.config.js
Fixes UICHKOUT-857.
No user-visible changes, just the use of a newer WSAPI.
=> UICHKOUT-857 Use new WSAPI for adding patron/staff notes to loans

CHANGELOG.md, src/components/PatronForm/PatronForm.js, src/components/PatronForm/PatronForm.test.js, test/jest/__mock__/stripesCore.mock.js
UI tests replacement with RTL/Jest for src/components/PatronForm/PatronForm.js
https://issues.folio.org/browse/UICHKOUT-833
=> UICHKOUT-833: UI tests replacement with RTL/Jest for src/components/PatronForm/PatronForm.js

CHANGELOG.md, package.json, src/components/ErrorModal/ErrorModal.test.js, src/components/NotificationModal/NotificationModal.test.js, src/components/PatronBlock/PatronBlock.test.js
Add possible for run axe tests
https://issues.folio.org/browse/UICHKOUT-858
=> UICHKOUT-858: Add possible for run axe tests

CHANGELOG.md, src/index.test.js
Fix issues with skipped tests
[UICHKOUT-864](https://issues.folio.org/browse/UICHKOUT-864)
=> UICHKOUT-864: Fix issues with skipped tests

CHANGELOG.md, src/components/CheckoutNoteModal/CheckoutNoteModal.test.js, src/components/ErrorModal/ErrorModal.test.js, src/components/ItemForm/ItemForm.test.js, src/components/MultipieceModal/MultipieceModal.test.js, src/components/NotificationModal/NotificationModal.test.js, src/components/OverrideModal/OverrideModal.test.js, src/components/PatronBlock/PatronBlock.test.js, src/components/PatronBlock/PatronBlockModal.test.js, src/components/PatronForm/PatronForm.test.js, src/components/ScanFooter/ScanFooter.test.js, src/components/ScanTotal/ScanTotal.test.js, src/components/SelectItemModal/SelectItemModal.test.js, src/components/UserDetail/Loans.test.js, src/components/UserDetail/UserDetails.test.js, src/components/ViewItem/ViewItem.test.js, src/components/ViewPatron/ViewPatron.test.js, src/util.test.js
Remove outdated imports
https://issues.folio.org/browse/UICHKOUT-867
=> UICHKOUT-867: Remove outdated imports

CHANGELOG.md, package.json
Use current optional dependencies
https://issues.folio.org/browse/UICHKOUT-870
=> UICHKOUT-870: Use current optional dependencies

CHANGELOG.md, src/ScanItems.js, src/ScanItems.test.js
Cover ScanItems.js by jest/RTL tests
[UICHKOUT-822](https://issues.folio.org/browse/UICHKOUT-822)
=> UICHKOUT-822: UI tests replacement with RTL/Jest for src/ScanItems.js

CHANGELOG.md, src/components/PatronForm/PatronForm.test.js, test/jest/__mock__/stripesComponents.mock.js
Increase coverage of PatronForm.
[UICHKOUT-879](https://issues.folio.org/browse/UICHKOUT-879)
=> UICHKOUT-879: Increase code coverage for PatronForm.js

CHANGELOG.md
Release v10.1.0
https://issues.folio.org/browse/UICHKOUT-902
=> Release v10.1.0

CHANGELOG.md, package.json
Update changelog and package.json
https://issues.folio.org/browse/UICHKOUT-902
=> UICHKOUT-902: Update changelog and package.json

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md
Remove bigtests from github actions
https://issues.folio.org/browse/UICHKOUT-908
=> UICHKOUT-908: Remove bigtests from github actions

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md
Update upload-artifact actions from v1 and v2 to v4
https://issues.folio.org/browse/UICHKOUT-917
=> UICHKOUT-917: Update upload-artifact actions from v1 and v2 to v4

CHANGELOG.md, src/ScanItems.js
Remove barcode trimming before it is sent to backend for processing
[UICHKOUT-903](https://folio-org.atlassian.net/browse/UICHKOUT-903)
=> UICHKOUT-903: Check out - Do not trim barcode before it is sent to backend for processing

CHANGELOG.md, package.json
Also support okapiInterfaces inventory 14.0
https://issues.folio.org/browse/UICHKOUT-922
=> UICHKOUT-922: Also support okapiInterfaces inventory 14.0

CHANGELOG.md, package.json
Verify changes in notes permissions.
https://folio-org.atlassian.net/browse/UICHKOUT-920
Update note permission
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> UICHKOUT-920: Update note permission

CHANGELOG.md, package.json, src/components/UserDetail/Loans.js, src/components/UserDetail/Loans.test.js, translations/ui-checkout/en.json
Review and cleanup Module Descriptor
Permissions renamed in according with Permissions naming convention ( https://folio-org.atlassian.net/wiki/spaces/FOLIJET/pages/156368925/Permissions+naming+convention )
https://issues.folio.org/browse/UICHKOUT-919
=> UICHKOUT-919: Review and cleanup Module Descriptor

CHANGELOG.md
Release ui-checkout v11.0.0 (Ramsons R2 2024)
https://issues.folio.org/browse/UICHKOUT-923
=> Release v11.0.0

CHANGELOG.md
Update changelog after release
[UICHKOUT-929](https://folio-org.atlassian.net/browse/UICHKOUT-929)
=> UICHKOUT-929: Update changelog after release

CHANGELOG.md
Update changelog after release
[UICHKOUT-931](https://folio-org.atlassian.net/browse/UICHKOUT-931)
=> UICHKOUT-931: Update changelog after release

CHANGELOG.md, src/components/ErrorModal/ErrorModal.js, src/components/OverrideModal/OverrideModal.js
React v19: refactor away from default props for functional components
https://folio-org.atlassian.net/browse/UICHKOUT-909
=> UICHKOUT-909: React v19: refactor away from default props for functional components

CHANGELOG.md, src/components/PatronBlock/PatronBlock.js, src/components/PatronBlock/PatronBlock.test.js, src/components/UserDetail/Loans.js, src/components/UserDetail/Loans.test.js, src/components/UserDetail/UserDetail.js, src/components/UserDetail/UserDetail.test.js, src/components/ViewPatron/ViewPatron.js, translations/ui-checkout/en.json
Fix accessibility issues related to not clear purpose of links.
[UICHKOUT-933](https://folio-org.atlassian.net/browse/UICHKOUT-933)
=> UICHKOUT-933: Fix accessibility issues

CHANGELOG.md, package.json, src/components/UserDetail/UserDetail.css, src/components/UserDetail/UserDetail.js, src/components/UserDetail/UserDetail.test.js, src/util.js, src/util.test.js
Display user pronouns at check out.
https://folio-org.atlassian.net/browse/UICHKOUT-932
=> UICHKOUT-932: Display user pronouns at check out

CHANGELOG.md, package.json
*BREAKING* Update react-intl to ^7
https://folio-org.atlassian.net/browse/UICHKOUT-944
=> UICHKOUT-944: *BREAKING* Update react-intl to ^7

CHANGELOG.md, src/components/PatronForm/PatronForm.js, src/components/PatronForm/PatronForm.test.js, test/jest/__mock__/stripesCore.mock.js
Add correct aria-label attribute to "Patron look-up" button.
[UICHKOUT-934](https://folio-org.atlassian.net/browse/UICHKOUT-934)
=> UICHKOUT-934: Add correct aria-label attribute to "Patron look-up" button

CHANGELOG.md, src/components/SelectItemModal/SelectItemModal.js, src/components/SelectItemModal/SelectItemModal.test.js
Implement support for fields without information
https://folio-org.atlassian.net/browse/UICHKOUT-945
=> UICHKOUT-945: Implement support for fields without information

CHANGELOG.md, package.json
Release v12.0.0
https://folio-org.atlassian.net/browse/UICHKOUT-950
=> Release v12.0.0

CHANGELOG.md, src/CheckOut.js, src/ModalManager.js, src/ScanItems.js, src/components/ItemForm/ItemForm.js, src/components/PatronBlock/PatronBlock.js, src/components/PatronForm/PatronForm.js, src/components/UserDetail/Loans.js, src/components/UserDetail/UserDetail.js, src/components/ViewItem/ViewItem.js, src/components/ViewPatron/ViewPatron.js, src/index.js
Reduce count of eslint errors after update eslint-config-stripes
https://issues.folio.org/browse/UICHKOUT-953
=> UICHKOUT-953: Reduce count of eslint errors after update eslint-config-stripes

CHANGELOG.md, package.json, src/components/UserDetail/Loans.js, src/components/UserDetail/Loans.test.js
Add sub-permissions for checkout permissions that do not have appropriate sub-permissions from other apps
https://issues.folio.org/browse/UICHKOUT-964
=> UICHKOUT-964: Add sub-permissions for checkout permissions that do not have appropriate sub-permissions from other apps
